# Mirrors cpp/app/hello/build.toml's [[targets]] "hello" executable.

load("//rules:cxx.bzl", "cxx_binary")

cxx_binary(
  name = "hello",
  srcs = ["main.cc"],
  include_dirs = ["cpp/lib"],
  deps = ["//cpp/adapters:example-vendor"],
  visibility = ["PUBLIC"],
)
