load("//rules:go.bzl", "go_library", "go_test")

go_library(
  name = "orderedatomic",
  srcs = [
    "atomic.go",
    "atomic_amd64.go",
    "atomic_amd64.s",
    "atomic_arm64.go",
    "atomic_arm64.s",
  ],
  visibility = ["PUBLIC"],
)

go_test(
  name = "orderedatomic_test",
  srcs = ["atomic_test.go"],
  deps = [":orderedatomic"],
  packages = ["./go/lib/internal/orderedatomic"],
)
