# Loader-wrapped Python hello application.

load("//rules:python.bzl", "py_binary")

py_binary(
  name = "hello",
  main = "main.py",
  deps = ["//python/lib/example:example"],
  pkg_name = "python-hello",
  visibility = ["PUBLIC"],
)
