load("//rules:go.bzl", "go_binary", "go_test")

go_binary(
  name = "bench_filewin",
  package = "./go/bench/filewin",
  srcs = ["main.go"],
  deps = [
    "//go/lib/filewin:filewin",
    "//go/lib/hostcpu:hostcpu",
  ],
  pkg_name = "go-filewin-bench",
  visibility = ["PUBLIC"],
)

go_test(
  coverage = False,
  name = "bench_filewin_test",
  srcs = ["main_test.go"],
  deps = [":bench_filewin"],
  packages = ["./go/bench/filewin"],
)
