#!/usr/bin/env python3
"""Generate toolchains/lock.bzl from tools.lock.toml for buck2 toolchain rules."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path
from typing import Any


# moon is retired by this migration; buck2 is the seed tool that runs the graph,
# not a target inside it. Every other locked tool becomes a buck2 toolchain.
SKIPPED_TOOLS = {"moon", "buck2"}

HEADER = (
  "# @generated by tools/gen_toolchain_lock.py from tools.lock.toml.\n"
  "# Do not edit by hand; run tools/gen_toolchain_lock.py to refresh.\n"
)


def load_artifacts(lock: Path) -> list[dict[str, Any]]:
  data = tomllib.loads(lock.read_text(encoding="utf-8"))
  artifacts = data.get("artifact", [])
  if not isinstance(artifacts, list):
    raise SystemExit(f"invalid tools.lock.toml: {lock}")
  return artifacts


def build_toolchains(artifacts: list[dict[str, Any]]) -> dict[str, dict[str, dict[str, str]]]:
  toolchains: dict[str, dict[str, dict[str, str]]] = {}
  for artifact in artifacts:
    tool = artifact["tool"]
    if tool in SKIPPED_TOOLS:
      continue
    target = artifact["target"]
    fields = {k: v for k, v in artifact.items() if k not in ("tool", "target")}
    toolchains.setdefault(tool, {})[target] = fields
  return toolchains


def render_value(value: Any) -> str:
  if isinstance(value, str):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
  raise SystemExit(f"unsupported toolchain lock value: {value!r}")


def render_starlark(toolchains: dict[str, dict[str, dict[str, str]]]) -> str:
  lines = [HEADER, "TOOLCHAINS = {"]
  for tool in sorted(toolchains):
    lines.append(f'  "{tool}": {{')
    for target in sorted(toolchains[tool]):
      lines.append(f'    "{target}": {{')
      fields = toolchains[tool][target]
      for key in sorted(fields):
        lines.append(f'      "{key}": {render_value(fields[key])},')
      lines.append("    },")
    lines.append("  },")
  lines.append("}")
  return "\n".join(lines) + "\n"


def main() -> None:
  parser = argparse.ArgumentParser()
  parser.add_argument("--lock", type=Path, default=Path("tools.lock.toml"))
  parser.add_argument("--output", type=Path, default=Path("toolchains/lock.bzl"))
  parser.add_argument("--check", action="store_true", help="fail if output would change")
  args = parser.parse_args()

  artifacts = load_artifacts(args.lock)
  rendered = render_starlark(build_toolchains(artifacts))

  if args.check:
    current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
    if current != rendered:
      raise SystemExit(f"{args.output} is stale; run tools/gen_toolchain_lock.py to refresh it")
    return

  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
  main()
