from collections.abc import Buffer


def add(left: int, right: int, /) -> int: ...
def xor_bytes(data: bytes, *, key: int) -> bytes: ...
def xor_kwb(*, data: bytes, key: int) -> bytes: ...
def xor_kwb_buf(*, data: Buffer, key: int) -> bytes: ...
def greet(*, name: str, excited: bool = False) -> str: ...
def prefix_join(items: list[object], *, prefix: str | None = None) -> str: ...
def xor_buffer(data: Buffer, *, key: int) -> bytes: ...
def repeat(data: bytes, *, times: int = 1) -> bytes: ...
def range(stop: int, /) -> list[int]: ...


class Point:
  def __init__(self, x: float, y: float, /) -> None: ...
  def __call__(self, dx: float, dy: float, /) -> Point: ...
  def dist(self) -> float: ...
  def scale(self, factor: float, /) -> None: ...
  def move(self, *, dx: float = 0.0, dy: float = 0.0) -> None: ...
